name: indoor-nav-dev
webhook_filter: "^refs/heads/dev$"
compose_files:
  - docker-compose-deploy.yaml
env_files:
  - /env/indoor-nav-dev.env
force_recreate: true
remove_orphans: true
timeout: 300
---
name: indoor-nav-prod
webhook_filter: "^refs/heads/main$"
compose_files:
  - docker-compose-deploy.yaml
env_files:
  - /env/indoor-nav-prod.env
force_recreate: true
remove_orphans: true
timeout: 300
