/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiDemoRouteImport } from './routes/ui-demo'
<<<<<<< HEAD
import { Route as ManageFloorRouteImport } from './routes/manage-floor'
=======
import { Route as TestSearchbarRouteImport } from './routes/test-searchbar'
import { Route as TestImportRouteImport } from './routes/test-import'
>>>>>>> f9df989 (added fuzzy search bar)
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UiDemoRoute = UiDemoRouteImport.update({
  id: '/ui-demo',
  path: '/ui-demo',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const ManageFloorRoute = ManageFloorRouteImport.update({
  id: '/manage-floor',
  path: '/manage-floor',
=======
const TestSearchbarRoute = TestSearchbarRouteImport.update({
  id: '/test-searchbar',
  path: '/test-searchbar',
  getParentRoute: () => rootRouteImport,
} as any)
const TestImportRoute = TestImportRouteImport.update({
  id: '/test-import',
  path: '/test-import',
>>>>>>> f9df989 (added fuzzy search bar)
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
<<<<<<< HEAD
  '/manage-floor': typeof ManageFloorRoute
=======
  '/test-import': typeof TestImportRoute
  '/test-searchbar': typeof TestSearchbarRoute
>>>>>>> f9df989 (added fuzzy search bar)
  '/ui-demo': typeof UiDemoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
<<<<<<< HEAD
  '/manage-floor': typeof ManageFloorRoute
=======
  '/test-import': typeof TestImportRoute
  '/test-searchbar': typeof TestSearchbarRoute
>>>>>>> f9df989 (added fuzzy search bar)
  '/ui-demo': typeof UiDemoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
<<<<<<< HEAD
  '/manage-floor': typeof ManageFloorRoute
=======
  '/test-import': typeof TestImportRoute
  '/test-searchbar': typeof TestSearchbarRoute
>>>>>>> f9df989 (added fuzzy search bar)
  '/ui-demo': typeof UiDemoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
<<<<<<< HEAD
  fullPaths: '/' | '/login' | '/manage-floor' | '/ui-demo' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/manage-floor' | '/ui-demo' | '/api/auth/$'
  id: '__root__' | '/' | '/login' | '/manage-floor' | '/ui-demo' | '/api/auth/$'
=======
  fullPaths:
    | '/'
    | '/calibrate-floor'
    | '/login'
    | '/test-import'
    | '/test-searchbar'
    | '/ui-demo'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calibrate-floor'
    | '/login'
    | '/test-import'
    | '/test-searchbar'
    | '/ui-demo'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/calibrate-floor'
    | '/login'
    | '/test-import'
    | '/test-searchbar'
    | '/ui-demo'
    | '/api/auth/$'
>>>>>>> f9df989 (added fuzzy search bar)
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
<<<<<<< HEAD
  ManageFloorRoute: typeof ManageFloorRoute
=======
  TestImportRoute: typeof TestImportRoute
  TestSearchbarRoute: typeof TestSearchbarRoute
>>>>>>> f9df989 (added fuzzy search bar)
  UiDemoRoute: typeof UiDemoRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-demo': {
      id: '/ui-demo'
      path: '/ui-demo'
      fullPath: '/ui-demo'
      preLoaderRoute: typeof UiDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/manage-floor': {
      id: '/manage-floor'
      path: '/manage-floor'
      fullPath: '/manage-floor'
      preLoaderRoute: typeof ManageFloorRouteImport
=======
    '/test-searchbar': {
      id: '/test-searchbar'
      path: '/test-searchbar'
      fullPath: '/test-searchbar'
      preLoaderRoute: typeof TestSearchbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-import': {
      id: '/test-import'
      path: '/test-import'
      fullPath: '/test-import'
      preLoaderRoute: typeof TestImportRouteImport
>>>>>>> f9df989 (added fuzzy search bar)
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
<<<<<<< HEAD
  ManageFloorRoute: ManageFloorRoute,
=======
  TestImportRoute: TestImportRoute,
  TestSearchbarRoute: TestSearchbarRoute,
>>>>>>> f9df989 (added fuzzy search bar)
  UiDemoRoute: UiDemoRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
