/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiDemoRouteImport } from './routes/ui-demo'
import { Route as ManageFloorRouteImport } from './routes/manage-floor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BenchRouteImport } from './routes/bench'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UiDemoRoute = UiDemoRouteImport.update({
  id: '/ui-demo',
  path: '/ui-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageFloorRoute = ManageFloorRouteImport.update({
  id: '/manage-floor',
  path: '/manage-floor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRoute = BenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/login': typeof LoginRoute
  '/manage-floor': typeof ManageFloorRoute
  '/ui-demo': typeof UiDemoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/login': typeof LoginRoute
  '/manage-floor': typeof ManageFloorRoute
  '/ui-demo': typeof UiDemoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/login': typeof LoginRoute
  '/manage-floor': typeof ManageFloorRoute
  '/ui-demo': typeof UiDemoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bench'
    | '/login'
    | '/manage-floor'
    | '/ui-demo'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bench' | '/login' | '/manage-floor' | '/ui-demo' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/bench'
    | '/login'
    | '/manage-floor'
    | '/ui-demo'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchRoute: typeof BenchRoute
  LoginRoute: typeof LoginRoute
  ManageFloorRoute: typeof ManageFloorRoute
  UiDemoRoute: typeof UiDemoRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-demo': {
      id: '/ui-demo'
      path: '/ui-demo'
      fullPath: '/ui-demo'
      preLoaderRoute: typeof UiDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-floor': {
      id: '/manage-floor'
      path: '/manage-floor'
      fullPath: '/manage-floor'
      preLoaderRoute: typeof ManageFloorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchRoute: BenchRoute,
  LoginRoute: LoginRoute,
  ManageFloorRoute: ManageFloorRoute,
  UiDemoRoute: UiDemoRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
